### ISSUE TITLE
Add language variables to language config files.

### ISSUE THREAD

**Issue by eguneys** [liaohuqiu/jekyll-multiple-languages#2]
For example instead of rendering with if like:
```
{% if language = 'en' %} Welcome {% else if language = 'tr' %} Hosgeldin {% endif %}
```
I could write `{% page.welcome %}`

and define welcome in `en.yml`

```
page:
  welcome: Welcome
```
and in `tr.yml`
```
page:
  welcome: Hosgeldin
```

**Comment by liaohuqiu** [comment]
* You can create a data file in the directory `_data`, for example: `i18n.yaml`:

    ```yaml
    en:
        previous_page: Previous
        next_page:    Next

    cn:
        previous_page: 上一页
        next_page:    下一页
    ```

* Then use the language variables in `pagination.html`:

    ```html
    <li>
    <a href="{{ "{{ paginator.previous_page_path " }}}}" aria-label="Previous">
        <span>{{ "{{ site.data.i18n[page.language].previous_page " }}}}</span>
    </a>
    </li>
    ```

And here is a sample: https://github.com/liaohuqiu/jekyll-multiple-languages-sample/blob/1e8d5f4ad7d8671163de2cf1468c66e5e8243143/_includes/pagination.html

Here is the site:  http://jekyll-langs-sample.liaohuqiu.net/
